<?php

namespace OC\MonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApprenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprenantRepository extends EntityRepository
{
}
